name: Check

on:
  - pull_request

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python and poetry
        uses: ./.github/actions/poetry

      - name: Check formatting
        run: |
          source $VENV
          poetry run ruff check

  type-checking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python and poetry
        uses: ./.github/actions/poetry

      - name: Type check
        run: |
          source $VENV
          poetry run pyright --warnings

  testing:
    strategy:
      matrix:
        python-version:
          - "3.11.2"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python and poetry
        uses: ./.github/actions/poetry

      - name: Run tests
        run: |
          source $VENV
          poetry run pytest
