name: Build and publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python and poetry
        uses: ./.github/actions/poetry

      - name: Build and Publish
        run: |
          poetry publish -p ${{ secrets.PYPI_TOKEN }} -u __token__ --build
        shell: bash